collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3163265
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 0.9012005
  brandColors:
    - '#E8DFB2'
    - '#CEBF91'
    - '#CFAB5C'
    - '#393831'
    - '#786444'
  lightness: 0.4763695
layout_spectrum: 0.2132116
name: Doge
